import Head from "next/head";

import Nav from "components/nav";
import About from "components/about";
// import Projects from "components/projects";
import Skills from "components/skills";
import Form from "components/form";

export default function Home() {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main>
        <Nav />
        <About />
        {/* <Projects /> */}
        <Skills />
        <Form />
      </main>
    </>
  );
}