import Head from "next/head";

import Nav from "components/customer/nav";
import About from "components/customer/about";
import Projects from "components/customer/projects";

export default function Home() {

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main>
        <Nav />
        <About />
        <Projects />
      </main>
    </>
  );
}